-- ============================================================
-- MIGRATION 020 -- les polices qui dessinent le meme latin cessent d'etre jouables
-- Requiert : 016, 017, 018, 019 appliquees
-- Source de verite : content/catalog/jumelles-eteintes.json
-- ============================================================
--
-- LE PROBLEME, MESURE ET NON SUPPOSE. Le jeu montre un mot latin et demande
-- quelle police le dessine. 351 polices jouables, en 61 familles, tracent ce
-- latin a l'identique : les neuf grandeurs mesurees dans leurs fichiers
-- different de moins d'un pour cent, chacune, et une famille n'existe que si
-- chaque membre est jumeau de chaque autre. Voir lib/game/twin-guard.ts.
--
-- CE QUE L'EXCLUSION EN MANCHE NE REPARE PAS. Deux jumelles ne peuvent deja
-- plus sortir ensemble dans une meme question, donc aucune question n'est
-- indecidable. Mais le joueur apprend une forme sous un nom, retrouve la meme
-- forme trois manches plus tard sous un autre nom, se trompe, et la repetition
-- espacee lui fait redescendre une police pour une distinction qui n'existe
-- pas. C'est l'apprentissage qui est casse, pas la question.
--
-- POURQUOI ETEINDRE ET NON RECULER EN `uncommon`. Reculer reporte la question.
-- Aucun niveau d'expertise ne rend "Noto Sans Old Permic" repondable : le latin
-- affiche est celui de Noto Sans et l'information n'est pas a l'ecran. Le joueur
-- expert la ratera exactement comme le debutant.
--
-- CE QUI RESTE JOUABLE. 56 polices canoniques, une par famille, et les 10
-- polices de 4 familles laissees intactes : 42dot Sans contre Asta Sans,
-- Al Yamama contre Ancizar Serif, El Messiri contre Philosopher contre ZCOOL
-- XiaoWei, et Lexend contre Lexend Deca contre Readex Pro. Ce sont de vraies
-- polices differentes, par des dessinateurs differents, qui mesurent pareil par
-- hasard. En eteindre une serait une perte seche et le choix serait arbitraire.
--
-- UNE FAMILLE ETEINTE EN ENTIER, sur decision du proprietaire. Dix-neuf Noto
-- Serif exotiques dont aucune n'est le Noto Serif ordinaire, et dont le latin
-- mesure differemment du sien : impossible de dire "garde Noto Serif", et
-- couronner "Noto Serif Khitan Small Script" n'aurait aucun sens.
--
-- RIEN N'EST DETRUIT. activation_status = false. La ligne garde son fichier,
-- ses metadonnees et son cluster visuel. Le retour arriere est un seul UPDATE.
--
-- LE MIROIR JSON PART DANS LE MEME COMMIT, par
-- scripts/sync_catalog_activation_json.py. Sans lui, un passage de
-- import_catalog_json.py rallumerait ces 285 lignes sans erreur et sans bruit,
-- exactement le piege rencontre sur les 108 Adobe en aout.

BEGIN;

UPDATE typefaces_core
SET activation_status = false
WHERE typeface_slug IN (
  'abyssinicasil',
  'afacadflux',
  'alumnisanssc',
  'amiriquran',
  'anekbangla',
  'anekdevanagari',
  'anekgujarati',
  'anekgurmukhi',
  'anekkannada',
  'anekmalayalam',
  'anekodia',
  'anektamil',
  'anektelugu',
  'anuphan',
  'arsenalsc',
  'atkinsonhyperlegiblenext',
  'baskervvillesc',
  'bodonimodasc',
  'bonanovasc',
  'bpmfhuninn',
  'cascadiamono',
  'cormorantgaramond',
  'ekmukta',
  'fragmentmonosc',
  'franklin_gothic_urw',
  'franklin_gothic_urw_compressed',
  'franklin_gothic_urw_condensed',
  'futura_100_latin_ext',
  'futura_100_latin_ext_book',
  'georgiapro',
  'hanuman',
  'helvetica_neue_world',
  'hindcolombo',
  'hindguntur',
  'hindjalandhar',
  'hindkochi',
  'hindmadurai',
  'hindmysuru',
  'hindsiliguri',
  'hindvadodara',
  'ibmplexsansarabic',
  'ibmplexsansdevanagari',
  'ibmplexsanshebrew',
  'ibmplexsanskr',
  'ibmplexsansthai',
  'ibmplexsansthailooped',
  'iosevkacharonmono',
  'kaiseiharunoumi',
  'kaiseiopti',
  'kaiseitokumin',
  'kohsantepheap',
  'lilex',
  'mada',
  'markazitextvfbeta',
  'mavenprovfbeta',
  'mochiypoppone',
  'mplus2',
  'mpluscodelatin',
  'muktamahee',
  'muktamalar',
  'muktavaani',
  'notokufiarabic',
  'notomusic',
  'notonaskharabic',
  'notonastaliqurdu',
  'notorashihebrew',
  'notosansadlam',
  'notosansadlamunjoined',
  'notosansanatolianhieroglyphs',
  'notosansarabic',
  'notosansarmenian',
  'notosansavestan',
  'notosansbalinese',
  'notosansbamum',
  'notosansbassavah',
  'notosansbatak',
  'notosansbengali',
  'notosansbhaiksuki',
  'notosansbrahmi',
  'notosansbuginese',
  'notosansbuhid',
  'notosanscanadianaboriginal',
  'notosanscarian',
  'notosanscaucasianalbanian',
  'notosanschakma',
  'notosanscham',
  'notosanscherokee',
  'notosanschorasmian',
  'notosanscoptic',
  'notosanscuneiform',
  'notosanscypriot',
  'notosanscyprominoan',
  'notosansdeseret',
  'notosansdevanagari',
  'notosansduployan',
  'notosansegyptianhieroglyphs',
  'notosanselbasan',
  'notosanselymaic',
  'notosansethiopic',
  'notosansgeorgian',
  'notosansglagolitic',
  'notosansgothic',
  'notosansgrantha',
  'notosansgujarati',
  'notosansgunjalagondi',
  'notosansgurmukhi',
  'notosanshanifirohingya',
  'notosanshanunoo',
  'notosanshatran',
  'notosanshk',
  'notosansimperialaramaic',
  'notosansindicsiyaqnumbers',
  'notosansinscriptionalpahlavi',
  'notosansinscriptionalparthian',
  'notosansjavanese',
  'notosanskaithi',
  'notosanskannada',
  'notosanskawi',
  'notosanskayahli',
  'notosanskharoshthi',
  'notosanskhmer',
  'notosanskhojki',
  'notosanskhudawadi',
  'notosanskr',
  'notosanslao',
  'notosanslaolooped',
  'notosanslepcha',
  'notosanslimbu',
  'notosanslineara',
  'notosanslinearb',
  'notosanslisu',
  'notosanslycian',
  'notosanslydian',
  'notosansmahajani',
  'notosansmalayalam',
  'notosansmandaic',
  'notosansmanichaean',
  'notosansmarchen',
  'notosansmasaramgondi',
  'notosansmath',
  'notosansmayannumerals',
  'notosansmedefaidrin',
  'notosansmeeteimayek',
  'notosansmendekikakui',
  'notosansmeroitic',
  'notosansmiao',
  'notosansmodi',
  'notosansmongolian',
  'notosansmro',
  'notosansmultani',
  'notosansmyanmar',
  'notosansnabataean',
  'notosansnagmundari',
  'notosansnandinagari',
  'notosansnewa',
  'notosansnewtailue',
  'notosansnko',
  'notosansnkounjoined',
  'notosansnushu',
  'notosansogham',
  'notosansolchiki',
  'notosansoldhungarian',
  'notosansolditalic',
  'notosansoldnortharabian',
  'notosansoldpermic',
  'notosansoldpersian',
  'notosansoldsogdian',
  'notosansoldsoutharabian',
  'notosansoldturkic',
  'notosansoriya',
  'notosansosage',
  'notosansosmanya',
  'notosanspahawhhmong',
  'notosanspalmyrene',
  'notosanspaucinhau',
  'notosansphagspa',
  'notosansphoenician',
  'notosanspsalterpahlavi',
  'notosansrejang',
  'notosansrunic',
  'notosanssamaritan',
  'notosanssaurashtra',
  'notosanssc',
  'notosansshavian',
  'notosanssiddham',
  'notosanssignwriting',
  'notosanssinhala',
  'notosanssogdian',
  'notosanssorasompeng',
  'notosanssoyombo',
  'notosanssundanese',
  'notosanssunuwar',
  'notosanssylotinagri',
  'notosanssymbols2',
  'notosanssyriac',
  'notosanssyriaceastern',
  'notosanssyriacwestern',
  'notosanstagalog',
  'notosanstagbanwa',
  'notosanstaile',
  'notosanstaitham',
  'notosanstaiviet',
  'notosanstakri',
  'notosanstamil',
  'notosanstamilsupplement',
  'notosanstangsa',
  'notosanstc',
  'notosanstelugu',
  'notosansthaana',
  'notosansthai',
  'notosansthailooped',
  'notosanstifinagh',
  'notosanstirhuta',
  'notosansugaritic',
  'notosansvai',
  'notosansvithkuqi',
  'notosanswancho',
  'notosanswarangciti',
  'notosansyi',
  'notosanszanabazarsquare',
  'notoserifahom',
  'notoserifarmenian',
  'notoserifbalinese',
  'notoserifbengali',
  'notoserifdevanagari',
  'notoserifdivesakuru',
  'notoserifdogra',
  'notoserifethiopic',
  'notoserifgeorgian',
  'notoserifgrantha',
  'notoserifgujarati',
  'notoserifgurmukhi',
  'notoserifhebrew',
  'notoserifhk',
  'notoserifkannada',
  'notoserifkhitansmallscript',
  'notoserifkhmer',
  'notoserifkhojki',
  'notoserifkr',
  'notoseriflao',
  'notoserifmakasar',
  'notoserifmalayalam',
  'notoserifnphmong',
  'notoserifolduyghur',
  'notoseriforiya',
  'notoserifottomansiyaq',
  'notoserifsc',
  'notoserifsinhala',
  'notoseriftamil',
  'notoseriftangut',
  'notoseriftc',
  'notoseriftelugu',
  'notoserifthai',
  'notoseriftibetan',
  'notoseriftoto',
  'notoserifvithkuqi',
  'notoserifyezidi',
  'nototraditionalnushu',
  'notoznamennymusicalnotation',
  'podkovavfbeta',
  'rasa',
  'reemkufifun',
  'roundedmplus1c',
  'sedansc',
  'shipporiminchob1',
  'spectralsc',
  'stacksansnotch',
  'tharlon',
  'tirobangla',
  'tirodevanagarihindi',
  'tirodevanagarimarathi',
  'tirodevanagarisanskrit',
  'tirogurmukhi',
  'tirokannada',
  'tirotamil',
  'tirotelugu',
  'tirra',
  'vazirmatn',
  'verdana_pro',
  'wdxllubrifontsc',
  'wdxllubrifonttc',
  'ysabeauoffice',
  'zcoolqingkehuangyou',
  'zenantiquesoft',
  'zenkakugothicantique'
)
  AND activation_status = true;

-- Une transaction qui leve annule tout, donc ce controle ne peut pas arriver
-- trop tard. Le patron vient de la 013, ou une prevision fausse de 14 lignes
-- avait justement ete arretee ici.
DO $$
DECLARE
  v_eteintes int;
  v_actives  int;
  v_canon    int;
BEGIN
  SELECT count(*) INTO v_eteintes FROM typefaces_core
  WHERE typeface_slug IN (
  'abyssinicasil',
  'afacadflux',
  'alumnisanssc',
  'amiriquran',
  'anekbangla',
  'anekdevanagari',
  'anekgujarati',
  'anekgurmukhi',
  'anekkannada',
  'anekmalayalam',
  'anekodia',
  'anektamil',
  'anektelugu',
  'anuphan',
  'arsenalsc',
  'atkinsonhyperlegiblenext',
  'baskervvillesc',
  'bodonimodasc',
  'bonanovasc',
  'bpmfhuninn',
  'cascadiamono',
  'cormorantgaramond',
  'ekmukta',
  'fragmentmonosc',
  'franklin_gothic_urw',
  'franklin_gothic_urw_compressed',
  'franklin_gothic_urw_condensed',
  'futura_100_latin_ext',
  'futura_100_latin_ext_book',
  'georgiapro',
  'hanuman',
  'helvetica_neue_world',
  'hindcolombo',
  'hindguntur',
  'hindjalandhar',
  'hindkochi',
  'hindmadurai',
  'hindmysuru',
  'hindsiliguri',
  'hindvadodara',
  'ibmplexsansarabic',
  'ibmplexsansdevanagari',
  'ibmplexsanshebrew',
  'ibmplexsanskr',
  'ibmplexsansthai',
  'ibmplexsansthailooped',
  'iosevkacharonmono',
  'kaiseiharunoumi',
  'kaiseiopti',
  'kaiseitokumin',
  'kohsantepheap',
  'lilex',
  'mada',
  'markazitextvfbeta',
  'mavenprovfbeta',
  'mochiypoppone',
  'mplus2',
  'mpluscodelatin',
  'muktamahee',
  'muktamalar',
  'muktavaani',
  'notokufiarabic',
  'notomusic',
  'notonaskharabic',
  'notonastaliqurdu',
  'notorashihebrew',
  'notosansadlam',
  'notosansadlamunjoined',
  'notosansanatolianhieroglyphs',
  'notosansarabic',
  'notosansarmenian',
  'notosansavestan',
  'notosansbalinese',
  'notosansbamum',
  'notosansbassavah',
  'notosansbatak',
  'notosansbengali',
  'notosansbhaiksuki',
  'notosansbrahmi',
  'notosansbuginese',
  'notosansbuhid',
  'notosanscanadianaboriginal',
  'notosanscarian',
  'notosanscaucasianalbanian',
  'notosanschakma',
  'notosanscham',
  'notosanscherokee',
  'notosanschorasmian',
  'notosanscoptic',
  'notosanscuneiform',
  'notosanscypriot',
  'notosanscyprominoan',
  'notosansdeseret',
  'notosansdevanagari',
  'notosansduployan',
  'notosansegyptianhieroglyphs',
  'notosanselbasan',
  'notosanselymaic',
  'notosansethiopic',
  'notosansgeorgian',
  'notosansglagolitic',
  'notosansgothic',
  'notosansgrantha',
  'notosansgujarati',
  'notosansgunjalagondi',
  'notosansgurmukhi',
  'notosanshanifirohingya',
  'notosanshanunoo',
  'notosanshatran',
  'notosanshk',
  'notosansimperialaramaic',
  'notosansindicsiyaqnumbers',
  'notosansinscriptionalpahlavi',
  'notosansinscriptionalparthian',
  'notosansjavanese',
  'notosanskaithi',
  'notosanskannada',
  'notosanskawi',
  'notosanskayahli',
  'notosanskharoshthi',
  'notosanskhmer',
  'notosanskhojki',
  'notosanskhudawadi',
  'notosanskr',
  'notosanslao',
  'notosanslaolooped',
  'notosanslepcha',
  'notosanslimbu',
  'notosanslineara',
  'notosanslinearb',
  'notosanslisu',
  'notosanslycian',
  'notosanslydian',
  'notosansmahajani',
  'notosansmalayalam',
  'notosansmandaic',
  'notosansmanichaean',
  'notosansmarchen',
  'notosansmasaramgondi',
  'notosansmath',
  'notosansmayannumerals',
  'notosansmedefaidrin',
  'notosansmeeteimayek',
  'notosansmendekikakui',
  'notosansmeroitic',
  'notosansmiao',
  'notosansmodi',
  'notosansmongolian',
  'notosansmro',
  'notosansmultani',
  'notosansmyanmar',
  'notosansnabataean',
  'notosansnagmundari',
  'notosansnandinagari',
  'notosansnewa',
  'notosansnewtailue',
  'notosansnko',
  'notosansnkounjoined',
  'notosansnushu',
  'notosansogham',
  'notosansolchiki',
  'notosansoldhungarian',
  'notosansolditalic',
  'notosansoldnortharabian',
  'notosansoldpermic',
  'notosansoldpersian',
  'notosansoldsogdian',
  'notosansoldsoutharabian',
  'notosansoldturkic',
  'notosansoriya',
  'notosansosage',
  'notosansosmanya',
  'notosanspahawhhmong',
  'notosanspalmyrene',
  'notosanspaucinhau',
  'notosansphagspa',
  'notosansphoenician',
  'notosanspsalterpahlavi',
  'notosansrejang',
  'notosansrunic',
  'notosanssamaritan',
  'notosanssaurashtra',
  'notosanssc',
  'notosansshavian',
  'notosanssiddham',
  'notosanssignwriting',
  'notosanssinhala',
  'notosanssogdian',
  'notosanssorasompeng',
  'notosanssoyombo',
  'notosanssundanese',
  'notosanssunuwar',
  'notosanssylotinagri',
  'notosanssymbols2',
  'notosanssyriac',
  'notosanssyriaceastern',
  'notosanssyriacwestern',
  'notosanstagalog',
  'notosanstagbanwa',
  'notosanstaile',
  'notosanstaitham',
  'notosanstaiviet',
  'notosanstakri',
  'notosanstamil',
  'notosanstamilsupplement',
  'notosanstangsa',
  'notosanstc',
  'notosanstelugu',
  'notosansthaana',
  'notosansthai',
  'notosansthailooped',
  'notosanstifinagh',
  'notosanstirhuta',
  'notosansugaritic',
  'notosansvai',
  'notosansvithkuqi',
  'notosanswancho',
  'notosanswarangciti',
  'notosansyi',
  'notosanszanabazarsquare',
  'notoserifahom',
  'notoserifarmenian',
  'notoserifbalinese',
  'notoserifbengali',
  'notoserifdevanagari',
  'notoserifdivesakuru',
  'notoserifdogra',
  'notoserifethiopic',
  'notoserifgeorgian',
  'notoserifgrantha',
  'notoserifgujarati',
  'notoserifgurmukhi',
  'notoserifhebrew',
  'notoserifhk',
  'notoserifkannada',
  'notoserifkhitansmallscript',
  'notoserifkhmer',
  'notoserifkhojki',
  'notoserifkr',
  'notoseriflao',
  'notoserifmakasar',
  'notoserifmalayalam',
  'notoserifnphmong',
  'notoserifolduyghur',
  'notoseriforiya',
  'notoserifottomansiyaq',
  'notoserifsc',
  'notoserifsinhala',
  'notoseriftamil',
  'notoseriftangut',
  'notoseriftc',
  'notoseriftelugu',
  'notoserifthai',
  'notoseriftibetan',
  'notoseriftoto',
  'notoserifvithkuqi',
  'notoserifyezidi',
  'nototraditionalnushu',
  'notoznamennymusicalnotation',
  'podkovavfbeta',
  'rasa',
  'reemkufifun',
  'roundedmplus1c',
  'sedansc',
  'shipporiminchob1',
  'spectralsc',
  'stacksansnotch',
  'tharlon',
  'tirobangla',
  'tirodevanagarihindi',
  'tirodevanagarimarathi',
  'tirodevanagarisanskrit',
  'tirogurmukhi',
  'tirokannada',
  'tirotamil',
  'tirotelugu',
  'tirra',
  'vazirmatn',
  'verdana_pro',
  'wdxllubrifontsc',
  'wdxllubrifonttc',
  'ysabeauoffice',
  'zcoolqingkehuangyou',
  'zenantiquesoft',
  'zenkakugothicantique'
  ) AND activation_status = false;

  IF v_eteintes <> 285 THEN
    RAISE EXCEPTION 'ANNULE : 285 polices attendues eteintes, trouve %', v_eteintes;
  END IF;

  SELECT count(*) INTO v_actives FROM typefaces_core WHERE activation_status;
  IF v_actives <> 994 THEN
    RAISE EXCEPTION 'ANNULE : 994 polices actives attendues, trouve %', v_actives;
  END IF;

  -- Le premier pool du debutant ne doit pas avoir bouge : la 019 vient de le
  -- porter a 23 polices Adobe sur 30 et aucune n'est dans cette liste.
  WITH eligible AS (
    SELECT typeface_slug, primary_category, difficulty_base, font_source::text AS src,
           ROW_NUMBER() OVER (PARTITION BY difficulty_base, primary_category
             ORDER BY (font_source::text = 'adobe') DESC, dreyfus_tier, rarity_tag, typeface_slug) AS cat_rank
    FROM typefaces_core
    WHERE activation_status AND rarity_tag = 'common' AND dreyfus_tier IN ('N','D')
  ),
  pe AS (SELECT * FROM eligible WHERE difficulty_base = 'easy'
         ORDER BY cat_rank, primary_category, typeface_slug LIMIT 12),
  pm AS (SELECT * FROM eligible WHERE difficulty_base = 'medium'
         ORDER BY cat_rank, primary_category, typeface_slug LIMIT 18)
  SELECT count(*) FILTER (WHERE src = 'adobe') INTO v_canon
  FROM (SELECT * FROM pe UNION ALL SELECT * FROM pm) t;

  IF v_canon <> 23 THEN
    RAISE EXCEPTION 'ANNULE : le premier pool doit garder 23 polices Adobe, trouve %', v_canon;
  END IF;
END $$;

COMMIT;
