"""
build_reviewed_promotion.py

Validate a completed editorial review and emit promotion-ready catalog fragments.

This script does not modify the main catalog automatically. It produces standalone
artifacts that can later be merged into `content/catalog/overrides/` once the
review has been accepted.

Supported review inputs:
- JSON template generated by `generate_editorial_review_template.py`
- CSV export of that same template

Usage:
    .venv/bin/python scripts/build_reviewed_promotion.py \
      --review-file content/catalog/batches/google-fonts-pilot-top-10/editorial-review/editorial-review-template.json \
      --staged-dir content/catalog/batches/google-fonts-pilot-top-10/promotion-stage \
      --catalog-dir content/catalog \
      --output-dir content/catalog/batches/google-fonts-pilot-top-10/promotion-ready
"""

from __future__ import annotations

import argparse
import csv
import json
from datetime import datetime, timezone
from pathlib import Path

REVIEW_FIELDS = [
    "sub_category",
    "visual_cluster_id",
    "dreyfus_tier",
    "difficulty_base",
    "rarity_tag",
    "year_tag",
    "weight_structure",
    "contrast_profile",
    "aperture_profile",
    "structural_signature",
]

STRUCTURAL_SIGNATURE_KEYS = {
    "a_type",
    "e_aperture",
    "axis",
    "contrast",
    "terminals",
    "serifs",
    "x_height",
    "fixed_width",
    "width",
    "caps_only",
    "distinctive_w",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build promotion-ready fragments from a completed editorial review.")
    parser.add_argument("--review-file", required=True)
    parser.add_argument("--staged-dir", required=True)
    parser.add_argument("--catalog-dir", default="content/catalog")
    parser.add_argument("--output-dir", required=True)
    parser.add_argument(
        "--approve-expert",
        action="store_true",
        help="Promote staged canonical Expert answers to approved and enable expert on the typeface records.",
    )
    return parser.parse_args()


def write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")


def load_payload(path: Path) -> dict:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict) or "records" not in payload or not isinstance(payload["records"], list):
        raise SystemExit(f"Invalid payload format in {path}")
    return payload


def normalize_empty(value: object) -> object:
    if value is None:
        return None
    if isinstance(value, str) and not value.strip():
        return None
    return value


def parse_structural_signature(value: object) -> dict | None:
    value = normalize_empty(value)
    if value is None:
        return None
    if isinstance(value, dict):
        return value
    if isinstance(value, str):
        try:
            parsed = json.loads(value)
        except json.JSONDecodeError as exc:
            raise ValueError(f"structural_signature must be valid JSON: {exc}") from exc
        if not isinstance(parsed, dict):
            raise ValueError("structural_signature must decode to a JSON object")
        return parsed
    raise ValueError("structural_signature must be a JSON object or a JSON string")


def load_review_records(path: Path) -> list[dict]:
    if path.suffix.lower() == ".json":
        payload = load_payload(path)
        return payload["records"]

    if path.suffix.lower() == ".csv":
        records: list[dict] = []
        with path.open("r", encoding="utf-8", newline="") as handle:
            reader = csv.DictReader(handle)
            for row in reader:
                review_fields = {field: normalize_empty(row.get(field)) for field in REVIEW_FIELDS}
                review_fields["structural_signature"] = parse_structural_signature(review_fields["structural_signature"])
                records.append(
                    {
                        "typeface_slug": row["typeface_slug"],
                        "display_name": normalize_empty(row.get("display_name")),
                        "primary_category": normalize_empty(row.get("primary_category")),
                        "designer": normalize_empty(row.get("designer")),
                        "license_type": normalize_empty(row.get("license_type")),
                        "priority": normalize_empty(row.get("priority")),
                        "lane": normalize_empty(row.get("lane")),
                        "runtime_ready": str(row.get("runtime_ready", "")).lower() == "true",
                        "review_fields": review_fields,
                        "review_status": normalize_empty(row.get("review_status")) or "pending",
                        "review_notes": row.get("review_notes") or "",
                    }
                )
        return records

    raise SystemExit(f"Unsupported review file extension: {path.suffix}")


def lookup_by_slug(records: list[dict]) -> dict[str, dict]:
    lookup: dict[str, dict] = {}
    for record in records:
        slug = record.get("typeface_slug")
        if slug:
            lookup[slug] = record
    return lookup


def validate_structural_signature(value: dict | None) -> list[str]:
    errors: list[str] = []
    if value is None:
        return ["structural_signature is missing"]
    missing_keys = STRUCTURAL_SIGNATURE_KEYS - set(value.keys())
    extra_keys = set(value.keys()) - STRUCTURAL_SIGNATURE_KEYS
    if missing_keys:
        errors.append(f"structural_signature missing keys: {sorted(missing_keys)}")
    if extra_keys:
        errors.append(f"structural_signature extra keys: {sorted(extra_keys)}")
    return errors


def validate_review_record(review_record: dict, staged_typeface: dict) -> list[str]:
    errors: list[str] = []
    status = review_record.get("review_status")
    if status != "approved":
        errors.append(f"review_status must be 'approved' (got {status!r})")

    review_fields = review_record.get("review_fields")
    if not isinstance(review_fields, dict):
        return errors + ["review_fields must be an object"]

    for field in REVIEW_FIELDS:
        value = normalize_empty(review_fields.get(field))
        if value is None:
            errors.append(f"missing review field: {field}")

    errors.extend(validate_structural_signature(review_fields.get("structural_signature")))

    if staged_typeface.get("_runtime_ready") is not True:
        errors.append("typeface is not runtime-ready in staged promotion data")

    return errors


def build_typeface_override(staged: dict, review: dict, approve_expert: bool) -> dict:
    review_fields = review["review_fields"]
    primary_category = review.get("primary_category") or staged["primary_category"]
    notes = [
        "promoted from reviewed candidate batch",
        f"source_batch={staged.get('_source_batch') or 'unknown'}",
        f"lane={staged.get('_lane') or 'unspecified'}",
        f"priority={staged.get('_priority') or 'unspecified'}",
        "editorial review completed before promotion",
    ]
    review_notes = (review.get("review_notes") or "").strip()
    if review_notes:
        notes.append(f"review_notes={review_notes}")
    return {
        "typeface_slug": staged["typeface_slug"],
        "display_name": staged["display_name"],
        "display_name_ascii": staged["display_name_ascii"],
        "primary_category": primary_category,
        "sub_category": review_fields["sub_category"],
        "visual_cluster_id": review_fields["visual_cluster_id"],
        "dreyfus_tier": review_fields["dreyfus_tier"],
        "difficulty_base": review_fields["difficulty_base"],
        "rarity_tag": review_fields["rarity_tag"],
        "activation_status": True,
        "font_source": staged["font_source"],
        "is_variable_font": staged["is_variable_font"],
        "year_tag": review_fields["year_tag"],
        "weight_structure": review_fields["weight_structure"],
        "contrast_profile": review_fields["contrast_profile"],
        "aperture_profile": review_fields["aperture_profile"],
        "structural_signature": review_fields["structural_signature"],
        "release_year": staged.get("release_year"),
        "designer": staged.get("designer"),
        "foundry": staged.get("foundry"),
        "license_type": staged.get("license_type"),
        "license_url": staged.get("license_url"),
        "fallback_stack": staged.get("fallback_stack"),
        "expert_enabled": bool(approve_expert),
        "min_mode": staged.get("min_mode", "training"),
        "qa_status": "approved",
        "notes": notes,
    }


def build_runtime_override(staged_runtime: dict) -> dict:
    return {
        "typeface_slug": staged_runtime["typeface_slug"],
        "file_role": staged_runtime["file_role"],
        "font_format": staged_runtime["font_format"],
        "weight": staged_runtime["weight"],
        "style": staged_runtime["style"],
        "source_path": staged_runtime["source_path"],
        "runtime_path": staged_runtime["runtime_path"],
        "file_size_bytes": staged_runtime["file_size_bytes"],
        "sha256_hash": staged_runtime["sha256_hash"],
        "runtime_status": staged_runtime["runtime_status"],
        "asset_origin": staged_runtime["asset_origin"],
        "verified_at_utc": staged_runtime["verified_at_utc"],
        "notes": list(staged_runtime.get("notes") or [])
        + ["promoted from reviewed candidate batch"],
    }


def build_expert_override(staged_expert: dict, approve_expert: bool) -> dict:
    return {
        "typeface_slug": staged_expert["typeface_slug"],
        "answer_text": staged_expert["answer_text"],
        "answer_normalized": staged_expert["answer_normalized"],
        "is_canonical": True,
        "locale": staged_expert.get("locale", "any"),
        "qa_status": "approved" if approve_expert else "review",
        "notes": list(staged_expert.get("notes") or [])
        + ["promotion fragment emitted from reviewed candidate batch"],
    }


def main() -> None:
    args = parse_args()
    review_file = Path(args.review_file).expanduser().resolve()
    staged_dir = Path(args.staged_dir).expanduser().resolve()
    catalog_dir = Path(args.catalog_dir).expanduser().resolve()
    output_dir = Path(args.output_dir).expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    staged_typefaces_payload = load_payload(staged_dir / "typefaces-core.staged.json")
    staged_runtime_payload = load_payload(staged_dir / "font-runtime-assets.staged.json")
    staged_expert_payload = load_payload(staged_dir / "expert-answer-keys.staged.json")
    current_catalog_payload = load_payload(catalog_dir / "typefaces-core.json")

    review_records = load_review_records(review_file)
    review_lookup = lookup_by_slug(review_records)
    staged_typefaces = lookup_by_slug(staged_typefaces_payload["records"])
    staged_runtime = lookup_by_slug(staged_runtime_payload["records"])
    staged_expert = lookup_by_slug(staged_expert_payload["records"])
    current_slugs = {record["typeface_slug"] for record in current_catalog_payload["records"]}

    report_records: list[dict] = []
    typeface_overrides: list[dict] = []
    runtime_overrides: list[dict] = []
    expert_overrides: list[dict] = []

    for slug, staged_typeface in staged_typefaces.items():
        review_record = review_lookup.get(slug)
        errors: list[str] = []
        warnings: list[str] = []

        if slug in current_slugs:
            warnings.append("typeface_slug already exists in current main catalog")

        if review_record is None:
            errors.append("missing review record")
        else:
            try:
                if isinstance(review_record.get("review_fields"), dict):
                    review_record["review_fields"]["structural_signature"] = parse_structural_signature(
                        review_record["review_fields"].get("structural_signature")
                    )
            except ValueError as exc:
                errors.append(str(exc))

            errors.extend(validate_review_record(review_record, staged_typeface))

        report_records.append(
            {
                "typeface_slug": slug,
                "status": "promotable" if not errors else "blocked",
                "errors": errors,
                "warnings": warnings,
            }
        )

        if errors:
            continue

        typeface_overrides.append(build_typeface_override(staged_typeface, review_record, args.approve_expert))
        runtime_overrides.append(build_runtime_override(staged_runtime[slug]))
        expert_overrides.append(build_expert_override(staged_expert[slug], args.approve_expert))

    promoted_total = len(typeface_overrides)
    blocked_total = len(report_records) - promoted_total

    meta = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "review_file": str(review_file),
        "staged_dir": str(staged_dir),
        "catalog_dir": str(catalog_dir),
        "counts": {
            "review_records_total": len(review_records),
            "staged_typefaces_total": len(staged_typefaces),
            "promotable_total": promoted_total,
            "blocked_total": blocked_total,
        },
        "approve_expert": args.approve_expert,
        "notes": [
            "This script emits promotion-ready fragments only.",
            "Main catalog overrides should be updated only after reviewing these fragments.",
        ],
    }

    write_json(output_dir / "promotion-validation-report.json", {"meta": meta, "records": report_records})

    if blocked_total:
        raise SystemExit(
            "Promotion review is incomplete. See "
            f"{output_dir / 'promotion-validation-report.json'}"
        )

    write_json(
        output_dir / "typefaces-core.promotion-ready.json",
        {"meta": meta, "records": typeface_overrides},
    )
    write_json(
        output_dir / "font-runtime-assets.promotion-ready.json",
        {"meta": meta, "records": runtime_overrides},
    )
    write_json(
        output_dir / "expert-answer-keys.promotion-ready.json",
        {"meta": meta, "records": expert_overrides},
    )


if __name__ == "__main__":
    main()
